### ISSUE TITLE
Set Up Keycloak Server for Authentication Infrastructure

### ISSUE THREAD

**Issue by altudev** [altudev/noobgg#57]
## 🎯 Goal

Set up and configure Keycloak server as the authentication provider for the noob.gg application. This will provide a robust, enterprise-grade identity and access management solution that integrates seamlessly with Auth.js 5.

### ✅ What We Have
- Docker and Docker Compose setup capability
- Database infrastructure (PostgreSQL)
- Backend API with Hono framework
- Frontend with Next.js 14
- Database schema with `user_keycloak_id` field ready

### ❌ What's Missing
- Keycloak server installation and configuration
- Keycloak realm setup for noob.gg
- Client configuration for the web application
- User federation and authentication flows
- Role and permission management
- Integration with existing database

#### 1.1 Create Keycloak Docker Compose Configuration
```yaml
# docker-compose.keycloak.yml
version: '3.8'

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    ports:
      - "5433:5432"  # Different port to avoid conflict with main app DB

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak-server
    environment:
      # Database configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      
      # Keycloak admin user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password_change_me
      
      # Keycloak configuration
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      
      # Development settings (change for production)
      KC_LOG_LEVEL: INFO
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - keycloak-network
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes  # Custom themes
      - ./keycloak/imports:/opt/keycloak/data/import  # Realm imports

volumes:
  keycloak_postgres_data:

networks:
  keycloak-network:
    driver: bridge
```

#### 1.2 Create Keycloak Startup Script
```bash
#!/bin/bash
# scripts/start-keycloak.sh

echo "🚀 Starting Keycloak server..."

# Create necessary directories
mkdir -p keycloak/themes
mkdir -p keycloak/imports

# Start Keycloak with Docker Compose
docker-compose -f docker-compose.keycloak.yml up -d

echo "⏳ Waiting for Keycloak to start..."
sleep 30

echo "✅ Keycloak should be available at: http://localhost:8080"
echo "🔑 Admin credentials: admin / admin_password_change_me"
echo "📝 Please change the admin password after first login!"
```

#### 1.3 Create Keycloak Stop Script
```bash
#!/bin/bash
# scripts/stop-keycloak.sh

echo "🛑 Stopping Keycloak server..."
docker-compose -f docker-compose.keycloak.yml down

echo "✅ Keycloak server stopped."
```

#### 2.1 Create NoobGG Realm Configuration
```json
{
  "realm": "noobgg",
  "displayName": "Noob.gg Gaming Platform",
  "displayNameHtml": "<div class=\"kc-logo-text\"><span>Noob.gg</span></div>",
  "enabled": true,
  "sslRequired": "external",
  "registrationAllowed": true,
  "registrationEmailAsUsername": true,
  "rememberMe": true,
  "verifyEmail": true,
  "loginWithEmailAllowed": true,
  "duplicateEmailsAllowed": false,
  "resetPasswordAllowed": true,
  "editUsernameAllowed": false,
  "bruteForceProtected": true,
  "permanentLockout": false,
  "maxFailureWaitSeconds": 900,
  "minimumQuickLoginWaitSeconds": 60,
  "waitIncrementSeconds": 60,
  "quickLoginCheckMilliSeconds": 1000,
  "maxDeltaTimeSeconds": 43200,
  "failureFactor": 30,
  "defaultSignatureAlgorithm": "RS256",
  "revokeRefreshToken": false,
  "refreshTokenMaxReuse": 0,
  "accessTokenLifespan": 300,
  "accessTokenLifespanForImplicitFlow": 900,
  "ssoSessionIdleTimeout": 1800,
  "ssoSessionMaxLifespan": 36000,
  "ssoSessionIdleTimeoutRememberMe": 0,
  "ssoSessionMaxLifespanRememberMe": 0,
  "offlineSessionIdleTimeout": 2592000,
  "offlineSessionMaxLifespanEnabled": false,
  "offlineSessionMaxLifespan": 5184000,
  "clientSessionIdleTimeout": 0,
  "clientSessionMaxLifespan": 0,
  "clientOfflineSessionIdleTimeout": 0,
  "clientOfflineSessionMaxLifespan": 0,
  "accessCodeLifespan": 60,
  "accessCodeLifespanUserAction": 300,
  "accessCodeLifespanLogin": 1800,
  "actionTokenGeneratedByAdminLifespan": 43200,
  "actionTokenGeneratedByUserLifespan": 300,
  "oauth2DeviceCodeLifespan": 600,
  "oauth2DevicePollingInterval": 5,
  "internationalizationEnabled": true,
  "supportedLocales": ["en", "tr"],
  "defaultLocale": "en",
  "loginTheme": "noobgg",
  "accountTheme": "noobgg",
  "adminTheme": "keycloak",
  "emailTheme": "noobgg"
}
```

#### 2.2 Create Client Configuration for Web App
```json
{
  "clientId": "noobgg-web",
  "name": "Noob.gg Web Application",
  "description": "Main web application client for noob.gg",
  "enabled": true,
  "clientAuthenticatorType": "client-secret",
  "secret": "your-client-secret-here",
  "redirectUris": [
    "http://localhost:3000/*",
    "https://noob.gg/*",
    "https://*.noob.gg/*"
  ],
  "webOrigins": [
    "http://localhost:3000",
    "https://noob.gg",
    "https://*.noob.gg"
  ],
  "protocol": "openid-connect",
  "publicClient": false,
  "bearerOnly": false,
  "consentRequired": false,
  "standardFlowEnabled": true,
  "implicitFlowEnabled": false,
  "directAccessGrantsEnabled": true,
  "serviceAccountsEnabled": false,
  "frontchannelLogout": true,
  "attributes": {
    "saml.assertion.signature": "false",
    "saml.force.post.binding": "false",
    "saml.multivalued.roles": "false",
    "saml.encrypt": "false",
    "oauth2.device.authorization.grant.enabled": "false",
    "backchannel.logout.revoke.offline.tokens": "false",
    "saml.server.signature": "false",
    "saml.server.signature.keyinfo.ext": "false",
    "exclude.session.state.from.auth.response": "false",
    "oidc.ciba.grant.enabled": "false",
    "saml.artifact.binding": "false",
    "backchannel.logout.session.required": "true",
    "client_credentials.use_refresh_token": "false",
    "saml_force_name_id_format": "false",
    "require.pushed.authorization.requests": "false",
    "saml.client.signature": "false",
    "tls.client.certificate.bound.access.tokens": "false",
    "saml.authnstatement": "false",
    "display.on.consent.screen": "false",
    "saml.onetimeuse.condition": "false"
  },
  "authenticationFlowBindingOverrides": {},
  "fullScopeAllowed": true,
  "nodeReRegistrationTimeout": -1,
  "defaultClientScopes": [
    "web-origins",
    "acr",
    "profile",
    "roles",
    "email"
  ],
  "optionalClientScopes": [
    "address",
    "phone",
    "offline_access",
    "microprofile-jwt"
  ]
}
```

#### 3.1 Define Application Roles
```json
{
  "roles": {
    "realm": [
      {
        "name": "user",
        "description": "Standard user role for registered players",
        "composite": false,
        "clientRole": false
      },
      {
        "name": "premium_user",
        "description": "Premium user with additional features",
        "composite": false,
        "clientRole": false
      },
      {
        "name": "moderator",
        "description": "Community moderator with moderation privileges",
        "composite": false,
        "clientRole": false
      },
      {
        "name": "admin",
        "description": "Administrator with full system access",
        "composite": false,
        "clientRole": false
      }
    ],
    "client": {
      "noobgg-web": [
        {
          "name": "lobby_create",
          "description": "Permission to create game lobbies"
        },
        {
          "name": "lobby_join",
          "description": "Permission to join game lobbies"
        },
        {
          "name": "profile_edit",
          "description": "Permission to edit user profile"
        },
        {
          "name": "leaderboard_view",
          "description": "Permission to view leaderboards"
        }
      ]
    }
  }
}
```

#### 3.2 Create Default User Groups
```json
{
  "groups": [
    {
      "name": "Players",
      "path": "/Players",
      "realmRoles": ["user"],
      "clientRoles": {
        "noobgg-web": ["lobby_join", "profile_edit", "leaderboard_view"]
      }
    },
    {
      "name": "Premium Players",
      "path": "/Premium Players",
      "realmRoles": ["premium_user"],
      "clientRoles": {
        "noobgg-web": ["lobby_create", "lobby_join", "profile_edit", "leaderboard_view"]
      }
    },
    {
      "name": "Moderators",
      "path": "/Moderators",
      "realmRoles": ["moderator"],
      "clientRoles": {
        "noobgg-web": ["lobby_create", "lobby_join", "profile_edit", "leaderboard_view"]
      }
    },
    {
      "name": "Administrators",
      "path": "/Administrators",
      "realmRoles": ["admin"],
      "clientRoles": {
        "noobgg-web": ["lobby_create", "lobby_join", "profile_edit", "leaderboard_view"]
      }
    }
  ]
}
```

#### 4.1 Create Noob.gg Theme Structure
```
keycloak/themes/noobgg/
├── login/
│   ├── theme.properties
│   ├── messages/
│   │   ├── messages_en.properties
│   │   └── messages_tr.properties
│   ├── resources/
│   │   ├── css/
│   │   │   └── login.css
│   │   ├── img/
│   │   │   ├── logo.png
│   │   │   └── favicon.ico
│   │   └── js/
│   │       └── login.js
│   └── template.ftl
├── account/
│   ├── theme.properties
│   ├── messages/
│   │   ├── messages_en.properties
│   │   └── messages_tr.properties
│   └── resources/
│       └── css/
│           └── account.css
└── email/
    ├── theme.properties
    ├── messages/
    │   ├── messages_en.properties
    │   └── messages_tr.properties
    └── html/
        ├── email-verification.ftl
        └── password-reset.ftl
```

#### 4.2 Login Theme Configuration
```properties
# keycloak/themes/noobgg/login/theme.properties
parent=keycloak
import=common/keycloak

styles=css/login.css

locales=en,tr
```

#### 4.3 Custom Login Styles
```css
/* keycloak/themes/noobgg/login/resources/css/login.css */
:root {
  --primary-color: #3b82f6;
  --primary-hover: #2563eb;
  --background-color: #f8fafc;
  --card-background: #ffffff;
  --text-primary: #1e293b;
  --text-secondary: #64748b;
  --border-color: #e2e8f0;
  --error-color: #ef4444;
  --success-color: #10b981;
}

body {
  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: var(--background-color);
  color: var(--text-primary);
}

.login-pf {
  background: var(--background-color);
}

.card-pf {
  background: var(--card-background);
  border: 1px solid var(--border-color);
  border-radius: 12px;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
}

.login-pf-header {
  text-align: center;
  margin-bottom: 2rem;
}

.login-pf-header h1 {
  color: var(--text-primary);
  font-size: 1.875rem;
  font-weight: 700;
  margin-bottom: 0.5rem;
}

.btn-primary {
  background-color: var(--primary-color);
  border-color: var(--primary-color);
  border-radius: 8px;
  font-weight: 500;
  padding: 0.75rem 1.5rem;
  transition: all 0.2s;
}

.btn-primary:hover {
  background-color: var(--primary-hover);
  border-color: var(--primary-hover);
  transform: translateY(-1px);
}

.form-control {
  border: 1px solid var(--border-color);
  border-radius: 8px;
  padding: 0.75rem 1rem;
  transition: border-color 0.2s;
}

.form-control:focus {
  border-color: var(--primary-color);
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

.alert-error {
  background-color: #fef2f2;
  border-color: var(--error-color);
  color: #991b1b;
  border-radius: 8px;
}

.alert-success {
  background-color: #f0fdf4;
  border-color: var(--success-color);
  color: #166534;
  border-radius: 8px;
}
```

#### 5.1 SMTP Configuration
```json
{
  "smtpServer": {
    "host": "smtp.gmail.com",
    "port": "587",
    "from": "noreply@noob.gg",
    "fromDisplayName": "Noob.gg",
    "replyTo": "support@noob.gg",
    "replyToDisplayName": "Noob.gg Support",
    "envelopeFrom": "noreply@noob.gg",
    "ssl": "false",
    "starttls": "true",
    "auth": "true",
    "user": "your-smtp-username",
    "password": "your-smtp-password"
  }
}
```

#### 5.2 Email Templates
```html
<!-- keycloak/themes/noobgg/email/html/email-verification.ftl -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>${msg("emailVerificationSubject")}</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { text-align: center; margin-bottom: 30px; }
        .logo { max-width: 200px; }
        .button { display: inline-block; padding: 12px 24px; background-color: #3b82f6; color: white; text-decoration: none; border-radius: 8px; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 14px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <img src="${url.resourcesPath}/img/logo.png" alt="Noob.gg" class="logo">
            <h1>Welcome to Noob.gg!</h1>
        </div>
        
        <p>Hi ${user.firstName!user.username},</p>
        
        <p>Thank you for registering with Noob.gg! To complete your registration, please verify your email address by clicking the button below:</p>
        
        <p style="text-align: center; margin: 30px 0;">
            <a href="${link}" class="button">Verify Email Address</a>
        </p>
        
        <p>If the button doesn't work, you can copy and paste this link into your browser:</p>
        <p style="word-break: break-all; color: #666;">${link}</p>
        
        <p>This link will expire in ${linkExpirationFormatter(linkExpiration)}.</p>
        
        <div class="footer">
            <p>If you didn't create an account with Noob.gg, you can safely ignore this email.</p>
            <p>&copy; 2024 Noob.gg. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
```

#### 6.1 Create Realm Export Script
```bash
#!/bin/bash
# scripts/export-keycloak-realm.sh

echo "📤 Exporting Keycloak realm configuration..."

# Export realm configuration
docker exec keycloak-server /opt/keycloak/bin/kc.sh export \
  --realm noobgg \
  --file /opt/keycloak/data/import/noobgg-realm-export.json \
  --users realm_file

# Copy exported file to host
docker cp keycloak-server:/opt/keycloak/data/import/noobgg-realm-export.json ./keycloak/imports/

echo "✅ Realm exported to ./keycloak/imports/noobgg-realm-export.json"
```

#### 6.2 Create Realm Import Script
```bash
#!/bin/bash
# scripts/import-keycloak-realm.sh

echo "📥 Importing Keycloak realm configuration..."

# Import realm configuration
docker exec keycloak-server /opt/keycloak/bin/kc.sh import \
  --file /opt/keycloak/data/import/noobgg-realm-export.json

echo "✅ Realm imported successfully"
```

#### 7.1 Production Docker Compose
```yaml
# docker-compose.keycloak.prod.yml
version: '3.8'

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-postgres-prod
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak-server-prod
    environment:
      # Database configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      
      # Keycloak admin user
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      
      # Production configuration
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HOSTNAME_STRICT: true
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HTTP_ENABLED: false
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
      
      # Security settings
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: WARN
      
      # Performance settings
      KC_CACHE: ispn
      KC_CACHE_STACK: kubernetes
    command: start
    ports:
      - "8443:8443"
    depends_on:
      - keycloak-db
    networks:
      - keycloak-network
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes
      - ./keycloak/imports:/opt/keycloak/data/import
      - ./keycloak/certs:/opt/keycloak/conf
    restart: unless-stopped

volumes:
  keycloak_postgres_data:

networks:
  keycloak-network:
    driver: bridge
```

#### 7.2 Environment Variables Template
```bash
# .env.keycloak
# Keycloak Database Configuration
KEYCLOAK_DB_NAME=keycloak_prod
KEYCLOAK_DB_USER=keycloak_user
KEYCLOAK_DB_PASSWORD=secure_password_here

# Keycloak Admin Configuration
KEYCLOAK_ADMIN_USER=admin
KEYCLOAK_ADMIN_PASSWORD=secure_admin_password_here

# Keycloak Server Configuration
KEYCLOAK_HOSTNAME=auth.noob.gg

# Client Configuration
KEYCLOAK_CLIENT_ID=noobgg-web
KEYCLOAK_CLIENT_SECRET=secure_client_secret_here
KEYCLOAK_ISSUER=https://auth.noob.gg/realms/noobgg

# SMTP Configuration
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=noreply@noob.gg
SMTP_PASSWORD=smtp_password_here
SMTP_FROM=noreply@noob.gg
SMTP_FROM_NAME=Noob.gg
```

### Phase 1: Basic Setup
- [ ] Create Docker Compose configuration for Keycloak
- [ ] Set up PostgreSQL database for Keycloak
- [ ] Configure Keycloak server with basic settings
- [ ] Create startup and stop scripts
- [ ] Test Keycloak admin console access

### Phase 2: Realm Configuration
- [ ] Create noobgg realm
- [ ] Configure realm settings (security, tokens, etc.)
- [ ] Set up internationalization (English/Turkish)
- [ ] Configure login and registration flows
- [ ] Test realm functionality

### Phase 3: Client Setup
- [ ] Create noobgg-web client
- [ ] Configure client settings and redirect URIs
- [ ] Generate and secure client secret
- [ ] Set up client scopes and mappers
- [ ] Test client authentication

### Phase 4: Roles and Permissions
- [ ] Define realm roles (user, premium_user, moderator, admin)
- [ ] Create client-specific roles
- [ ] Set up user groups with default roles
- [ ] Configure role mappings
- [ ] Test role assignment

### Phase 5: Custom Theming
- [ ] Create noobgg theme structure
- [ ] Design custom login page
- [ ] Create account management theme
- [ ] Design email templates
- [ ] Test theme across different browsers

### Phase 6: Email Configuration
- [ ] Set up SMTP server configuration
- [ ] Configure email templates
- [ ] Test email verification flow
- [ ] Test password reset flow
- [ ] Verify email deliverability

### Phase 7: Import/Export
- [ ] Create realm export script
- [ ] Create realm import script
- [ ] Test backup and restore procedures
- [ ] Document configuration management

### Phase 8: Production Setup
- [ ] Create production Docker Compose
- [ ] Set up SSL/TLS certificates
- [ ] Configure production environment variables
- [ ] Set up monitoring and logging
- [ ] Test production deployment

### Phase 9: Security Hardening
- [ ] Enable brute force protection
- [ ] Configure session timeouts
- [ ] Set up proper CORS policies
- [ ] Enable security headers
- [ ] Conduct security audit

### Phase 10: Integration Testing
- [ ] Test with Auth.js 5 integration
- [ ] Verify user registration flow
- [ ] Test login/logout functionality
- [ ] Validate role-based access
- [ ] Test mobile compatibility

### Visual Design
- **Brand Consistency**: Match noob.gg visual identity
- **Responsive Design**: Work on all device sizes
- **Modern UI**: Clean, modern interface design
- **Accessibility**: WCAG 2.1 AA compliance

### User Experience
- **Intuitive Flow**: Clear registration and login process
- **Fast Performance**: Quick authentication responses
- **Error Handling**: Clear error messages and recovery
- **Multi-language**: Support for English and Turkish

### Technical KPIs
- Keycloak server uptime > 99.9%
- Authentication response time < 500ms
- Zero security vulnerabilities
- Successful backup/restore procedures

### User Experience KPIs
- Registration completion rate > 90%
- Login success rate > 98%
- Email verification rate > 85%
- User satisfaction with auth flow > 4.5/5

### Security
- **Data Protection**: GDPR compliance for user data
- **Secure Communication**: TLS 1.3 for all connections
- **Token Security**: Proper JWT handling and validation
- **Audit Logging**: Comprehensive security event logging

### Performance
- **Caching**: Efficient token and session caching
- **Database Optimization**: Proper indexing and queries
- **Load Balancing**: Support for horizontal scaling
- **CDN Integration**: Static asset delivery optimization

### Monitoring
- **Health Checks**: Automated service monitoring
- **Metrics Collection**: Performance and usage metrics
- **Alerting**: Proactive issue notification
- **Log Aggregation**: Centralized logging system

## ✅ Acceptance Criteria

- [ ] Keycloak server runs successfully in Docker
- [ ] Admin console is accessible and functional
- [ ] Noobgg realm is properly configured
- [ ] Client authentication works with Auth.js 5
- [ ] User registration and verification flow works
- [ ] Password reset functionality works
- [ ] Custom theme is applied and responsive
- [ ] Email notifications are sent successfully
- [ ] Role-based access control is functional
- [ ] Production deployment is secure and scalable
- [ ] Backup and restore procedures work
- [ ] Documentation is complete and accurate

## 📚 Resources

- [Keycloak Documentation](https://www.keycloak.org/documentation)
- [Keycloak Docker Guide](https://www.keycloak.org/getting-started/getting-started-docker)
- [Keycloak Themes Guide](https://www.keycloak.org/docs/latest/server_development/#_themes)
- [OpenID Connect Specification](https://openid.net/connect/)
- [Docker Compose Documentation](https://docs.docker.com/compose/)

## 🏷️ Labels
`infrastructure` `keycloak` `authentication` `docker` `security` `backend` `devops` `enhancement`

## 📋 Dependencies

- **Blocks**: Issue #56 (Login/Logout/Register UI Components)
- **Blocks**: Issue #53 (Auth.js 5 with Keycloak Provider Integration)
- **Requires**: Docker and Docker Compose setup
- **Requires**: Domain configuration for production
- **Enables**: Complete authentication infrastructure
- **Enables**: User management and role-based access

---

**Note for Junior Developers**: This issue focuses on setting up the Keycloak server infrastructure. Start with the basic Docker setup and gradually add more advanced features. Make sure to test each phase thoroughly before moving to the next one. Keep security in mind throughout the implementation process!
